version: '3.1'
services:
  database-manga:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'shinobidatabase'
      MYSQL_USER: 'hokage'
      MYSQL_PASSWORD: 'hokage'
      MYSQL_ROOT_PASSWORD: 'hokage'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: